export const ACTION_TYPE = {
	LOGOUT: 'LOGOUT',
	SET_EDITING_POST: 'SET_EDITING_POST',
	UPDATE_EDITING_POST: 'UPDATE_EDITING_POST',
	CLEAR_EDITING_POST: 'CLEAR_EDITING_POST',
	CREATE_NEW_POST: 'CREATE_NEW_POST',
	
};
