export const ACTION_TYPE = {
	SET_FRIENDS_DATA: 'SET_FRIENDS_DATA',
	SET_FRIENDS_LOADING: 'SET_FRIENDS_LOADING',
	SET_FRIENDS_ERROR: 'SET_FRIENDS_ERROR',
	ADD_DELETED_USER_ID: 'ADD_DELETED_USER_ID',
	CLEAR_DELETED_USERS: 'CLEAR_DELETED_USERS'
};
