export const ACTION_TYPE = {
	SET_COMMENTS: 'SET_COMMENTS',
	ADD_COMMENT: 'ADD_COMMENT',
	UPDATE_COMMENT: 'UPDATE_COMMENT',
	DELETE_COMMENT: 'DELETE_COMMENT',
	SET_COMMENTS_LOADING: 'SET_COMMENTS_LOADING',
	SET_COMMENTS_ERROR: 'SET_COMMENTS_ERROR',
	SET_COMMENT_LIKE: 'SET_COMMENT_LIKE',
	LOGOUT: 'LOGOUT',
};
