export const ACTION_TYPE = {
	SET_LIKED_POSTS: 'SET_LIKED_POSTS',
	SET_LIKED_POSTS_LOADING: 'SET_LIKED_POSTS_LOADING',
	UPDATE_LIKED_POST: 'UPDATE_LIKED_POST',
	DELETE_LIKED_POST: 'DELETE_LIKED_POST',
	LOGOUT: 'LOGOUT'
};
