export const ACTION_TYPE = {
	SET_PUBLICATIONS_USER: 'SET_PUBLICATIONS_USER',
	SET_PUBLICATIONS_LOADING: 'SET_PUBLICATIONS_LOADING',
	ADDING_NEW_POST: 'ADDING_NEW_POST',
	DELETE_POST: 'DELETE_POST',
	UPDATE_POST_IN_LIST:'UPDATE_POST_IN_LIST',
	LOGOUT: 'LOGOUT'
};
